FROM python:3.12-slim

WORKDIR /app

COPY requirements/train.txt requirements/train.txt

RUN pip install --no-cache-dir -r requirements/train.txt

COPY src/ src/
COPY configs/ configs/

CMD ["python", "-m", "src.train", "--config", "configs/sanity_config.yaml"]