apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-data-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
