FROM python:3.12-slim AS base

WORKDIR /app

COPY requirements/train.txt requirements/train.txt

RUN pip install --no-cache-dir -r requirements/train.txt


FROM base AS training

WORKDIR /app

COPY src/ src/
COPY configs/ configs/

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "-m", "src.train"]